name: CI workflow
on: push
jobs:
  sast-scan:
    name: Run BANDIT SAST scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: install bandit
      run: pip install bandit
    - name: run bandit scan on code
      run: bandit -r -lll -ii . -f json -o bandit-report.json

    - name: Upload artifact
      uses: actions/upload-artifact@v7.0.1
      if: always()
      with:
        name: bandit-report
        path: bandit-report.json
  docker-image-scan:
    name: build image and run image scan
    runs-on: ubuntu-latest
    steps:
    - name: checkout the code
      uses: actions/checkout@v2
    - name: setup docker
      uses: docker/setup-docker-action@v5.1.0
      with: 
        version: latest
    - name: build image
      run: docker build -f Dockerfile -t pygoat:latest .
    - name: using docker scout to scan the image
      uses: docker/scout-action@v1.20.4
      with:
       dockerhub-user: ${{ secrets.DOCKER_USER }}
       dockerhub-password: ${{ secrets.DOCKER_PASS }}
       command: quickview,cves,recommendations
       only-severities: critical
       sarif-file: scout-report.sarif
    - name: upload the report
      uses: actions/upload-artifact@v7.0.1
      if: always()
      with:
        name: scout-report
        path: scout-report.sarif
